# Generated by Django 5.2.4 on 2026-01-16 20:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id_chauffeur', models.AutoField(db_column='id_chauffeur', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nom', max_length=100)),
                ('telephone', models.CharField(blank=True, db_column='telephone', max_length=20, null=True)),
            ],
            options={
                'db_table': 'chauffeur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id_trajet', models.AutoField(db_column='id_trajet', primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(db_column='ville_depart', max_length=100)),
                ('ville_arrivee', models.CharField(db_column='ville_arrivee', max_length=100)),
                ('distance_km', models.DecimalField(db_column='distance_km', decimal_places=2, max_digits=6)),
                ('duree_prevue', models.DurationField(blank=True, db_column='duree_prevue', null=True)),
            ],
            options={
                'db_table': 'trajet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(db_column='id_vehicule', primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_column='matricule', max_length=20, unique=True)),
                ('capacite', models.PositiveIntegerField(db_column='capacite')),
                ('type', models.CharField(db_column='type', max_length=50)),
                ('kilometrage_total', models.DecimalField(db_column='kilometrage_total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vehicule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id_voyage', models.AutoField(db_column='id_voyage', primary_key=True, serialize=False)),
                ('date_depart', models.DateField(db_column='date_depart')),
                ('heure_depart', models.TimeField(db_column='heure_depart')),
                ('prix_par_siege', models.DecimalField(db_column='prix_par_siege', decimal_places=2, max_digits=8)),
                ('chauffeur', models.ForeignKey(db_column='id_chauffeur', on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='SGT.chauffeur')),
                ('trajet', models.ForeignKey(db_column='id_trajet', on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='SGT.trajet')),
                ('vehicule', models.ForeignKey(db_column='id_vehicule', on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='SGT.vehicule')),
            ],
            options={
                'db_table': 'voyage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], db_column='role', default='CLIENT', max_length=10)),
                ('telephone', models.CharField(blank=True, db_column='telephone', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(db_column='id_reservation', primary_key=True, serialize=False)),
                ('nom_passager', models.CharField(blank=True, db_column='nom_passager', max_length=100, null=True)),
                ('telephone_passager', models.CharField(blank=True, db_column='telephone_passager', max_length=20, null=True)),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces (Agence)'), ('BANKILY', 'Bankily'), ('MASRVI', 'Masrvi'), ('SEDAD', 'Sedad'), ('GAZA_PAY', 'Gaza Pay')], db_column='mode_paiement', default='CASH', max_length=20)),
                ('ref_paiement', models.CharField(blank=True, db_column='ref_paiement', max_length=50, null=True)),
                ('nb_sieges', models.PositiveIntegerField(db_column='nb_sieges', default=1)),
                ('statut', models.CharField(choices=[('réservé', 'Réservé'), ('annulé', 'Annulé'), ('payé', 'Payé')], db_column='statut', default='réservé', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True, db_column='date_reservation')),
                ('voyage', models.ForeignKey(db_column='id_voyage', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='SGT.voyage')),
                ('client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
    ]
