# Generated by Django 5.2.4 on 2026-01-16 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': True, 'ordering': ['-date_reservation']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nb_sieges',
            field=models.PositiveIntegerField(db_column='nb_sieges', default=1, validators=[django.core.validators.MinValueValidator(1, message='Il faut réserver au moins 1 place.')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('réservé', 'Réservé'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('payé', 'Payé')], db_column='statut', default='réservé', max_length=20),
        ),
    ]
