# Generated by Django 5.2.4 on 2026-01-17 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nom_passager',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ref_paiement',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='telephone_passager',
        ),
        migrations.AddField(
            model_name='reservation',
            name='preuve_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut_paiement',
            field=models.CharField(default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nb_sieges',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('réservé', 'Réservé'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('payé', 'Payé')], default='réservé', max_length=20),
        ),
    ]
