# Generated by Django 5.2.4 on 2026-01-19 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('CLIENT', 'Client'), ('SUPERVISEUR', 'Superviseur')], db_column='role', default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='prix_par_siege',
            field=models.DecimalField(db_column='prix_par_siege', decimal_places=2, default=Decimal('1.50'), max_digits=10),
        ),
    ]
