# Generated by Django 5.2.4 on 2026-01-23 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0004_alter_user_role_alter_voyage_prix_par_siege'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='autre_nom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='autre_tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_creees', to=settings.AUTH_USER_MODEL),
        ),
    ]
