# Generated by Django 5.2.4 on 2026-01-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0006_alter_reservation_statut_phoneotp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoneverification',
            name='user',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('réservé', 'Réservé'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('payé', 'Payé')], default='réservé', max_length=20),
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.DeleteModel(
            name='UserPhoneVerification',
        ),
    ]
