# Generated by Django 5.2.8 on 2026-02-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0007_remove_userphoneverification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='methode_paiement',
            field=models.CharField(choices=[('cash', 'Espèces (Cash)'), ('bankily', 'Bankily'), ('masrvi', 'Masrvi')], default='cash', max_length=20),
        ),
    ]
