# Generated by Django 5.2.8 on 2026-02-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0008_reservation_methode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('bankily', 'Bankily'), ('masrvi', 'Masrvi'), ('sedad', 'Sedad'), ('ghaza_pay', 'Ghaza Pay'), ('bii', 'Bii'), ('moov_money', 'Moov Money')], default='bankily', max_length=30, null=True),
        ),
    ]
