# Generated by Django 5.2.4 on 2026-02-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0009_alter_reservation_methode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
