# Generated by Django 5.2.4 on 2026-02-03 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGT', '0010_companycontact_paymentoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISEUR', 'Superviseur'), ('AGENT', 'Agent'), ('CLIENT', 'Client'), ('CHAUFFEUR', 'Chauffeur')], db_column='role', default='CLIENT', max_length=20),
        ),
    ]
